"""add routine fields

Revision ID: 02d100681e1c
Revises: 04471edba56c
Create Date: 2026-08-22 09:53:55.664048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02d100681e1c'
down_revision: Union[str, None] = '04471edba56c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routines', sa.Column('days_of_week', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('routines', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('routines', sa.Column('end_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routines', 'end_time')
    op.drop_column('routines', 'start_time')
    op.drop_column('routines', 'days_of_week')
    # ### end Alembic commands ###
