"""Update PushSubscription to use push_token

Revision ID: 04471edba56c
Revises: 5b32740153f7
Create Date: 2026-08-21 12:29:29.829818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04471edba56c'
down_revision: Union[str, None] = '5b32740153f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push_subscriptions', sa.Column('push_token', sa.String(length=255), nullable=False))
    op.drop_column('push_subscriptions', 'auth')
    op.drop_column('push_subscriptions', 'endpoint')
    op.drop_column('push_subscriptions', 'p256dh')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push_subscriptions', sa.Column('p256dh', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('push_subscriptions', sa.Column('endpoint', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.add_column('push_subscriptions', sa.Column('auth', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('push_subscriptions', 'push_token')
    # ### end Alembic commands ###
