"""Add PushSubscription model

Revision ID: 63a914905b59
Revises: 004
Create Date: 2026-08-02 18:43:16.945575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63a914905b59'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_logs', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('activity_logs', 'status',
               existing_type=postgresql.ENUM('started', 'completed', 'skipped', name='activitystatus'),
               nullable=False,
               existing_server_default=sa.text("'started'::activitystatus"))
    op.alter_column('activity_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_analyses', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('ai_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('notifications', 'notification_type',
               existing_type=postgresql.ENUM('schedule_generated', 'task_reminder', 'task_completed', 'task_missed', 'system', name='notificationtype'),
               nullable=False,
               existing_server_default=sa.text("'system'::notificationtype"))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reminders', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('reminders', 'reminder_type',
               existing_type=postgresql.ENUM('task', 'meal', 'water', 'sleep', 'medication', 'custom', name='remindertype'),
               nullable=False,
               existing_server_default=sa.text("'custom'::remindertype"))
    op.alter_column('reminders', 'is_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('reminders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('routines', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('routines', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('routines', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('routines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('schedules', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('schedules', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'urgent', name='taskpriority'),
               nullable=False,
               existing_server_default=sa.text("'medium'::taskpriority"))
    op.alter_column('schedules', 'status',
               existing_type=postgresql.ENUM('draft', 'active', 'completed', 'cancelled', name='schedulestatus'),
               nullable=False,
               existing_server_default=sa.text("'active'::schedulestatus"))
    op.alter_column('schedules', 'category',
               existing_type=postgresql.ENUM('work', 'study', 'health', 'personal', 'meal', 'sleep', 'other', name='taskcategory'),
               nullable=False,
               existing_server_default=sa.text("'other'::taskcategory"))
    op.alter_column('schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tasks', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'urgent', name='taskpriority'),
               nullable=False,
               existing_server_default=sa.text("'medium'::taskpriority"))
    op.alter_column('tasks', 'category',
               existing_type=postgresql.ENUM('work', 'study', 'health', 'personal', 'meal', 'sleep', 'other', name='taskcategory'),
               nullable=False,
               existing_server_default=sa.text("'other'::taskcategory"))
    op.alter_column('tasks', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('60'))
    op.alter_column('tasks', 'travel_time_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('tasks', 'is_fixed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tasks', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('pending', 'in_progress', 'completed', 'skipped', 'cancelled', name='taskstatus'),
               nullable=False,
               existing_server_default=sa.text("'pending'::taskstatus"))
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('pending', 'in_progress', 'completed', 'skipped', 'cancelled', name='taskstatus'),
               nullable=True,
               existing_server_default=sa.text("'pending'::taskstatus"))
    op.alter_column('tasks', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('tasks', 'is_fixed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('tasks', 'travel_time_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('tasks', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('60'))
    op.alter_column('tasks', 'category',
               existing_type=postgresql.ENUM('work', 'study', 'health', 'personal', 'meal', 'sleep', 'other', name='taskcategory'),
               nullable=True,
               existing_server_default=sa.text("'other'::taskcategory"))
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'urgent', name='taskpriority'),
               nullable=True,
               existing_server_default=sa.text("'medium'::taskpriority"))
    op.alter_column('tasks', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('tasks', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('schedules', 'category',
               existing_type=postgresql.ENUM('work', 'study', 'health', 'personal', 'meal', 'sleep', 'other', name='taskcategory'),
               nullable=True,
               existing_server_default=sa.text("'other'::taskcategory"))
    op.alter_column('schedules', 'status',
               existing_type=postgresql.ENUM('draft', 'active', 'completed', 'cancelled', name='schedulestatus'),
               nullable=True,
               existing_server_default=sa.text("'active'::schedulestatus"))
    op.alter_column('schedules', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'urgent', name='taskpriority'),
               nullable=True,
               existing_server_default=sa.text("'medium'::taskpriority"))
    op.alter_column('schedules', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('routines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('routines', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('routines', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('routines', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('reminders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reminders', 'is_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('reminders', 'reminder_type',
               existing_type=postgresql.ENUM('task', 'meal', 'water', 'sleep', 'medication', 'custom', name='remindertype'),
               nullable=True,
               existing_server_default=sa.text("'custom'::remindertype"))
    op.alter_column('reminders', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'notification_type',
               existing_type=postgresql.ENUM('schedule_generated', 'task_reminder', 'task_completed', 'task_missed', 'system', name='notificationtype'),
               nullable=True,
               existing_server_default=sa.text("'system'::notificationtype"))
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('ai_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_analyses', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('activity_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('activity_logs', 'status',
               existing_type=postgresql.ENUM('started', 'completed', 'skipped', name='activitystatus'),
               nullable=True,
               existing_server_default=sa.text("'started'::activitystatus"))
    op.alter_column('activity_logs', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
