"""add travel_time_minutes to tasks and drop routine_text

Revision ID: 6c48a7a3f491
Revises: 005_phase2_schema
Create Date: 2026-08-19 23:19:50.444336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c48a7a3f491'
down_revision: Union[str, None] = '005_phase2_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_stats_user_id'), 'user_stats', ['user_id'], unique=True)
    op.create_table('task_occurrences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'in_progress', 'completed', 'skipped', 'cancelled', name='taskstatus', create_type=False), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('travel_time_minutes', sa.Integer(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_occurrences_date'), 'task_occurrences', ['date'], unique=False)
    op.create_index(op.f('ix_task_occurrences_task_id'), 'task_occurrences', ['task_id'], unique=False)
    op.create_index('ix_task_occurrences_user_date', 'task_occurrences', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_task_occurrences_user_id'), 'task_occurrences', ['user_id'], unique=False)
    op.create_index('ix_task_occurrences_user_status', 'task_occurrences', ['user_id', 'status'], unique=False)
    op.add_column('activity_logs', sa.Column('task_occurrence_id', sa.UUID(), nullable=True))
    op.alter_column('activity_logs', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('activity_logs', 'status',
               existing_type=postgresql.ENUM('started', 'completed', 'skipped', name='activitystatus'),
               nullable=False,
               existing_server_default=sa.text("'started'::activitystatus"))
    op.alter_column('activity_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_activity_logs_task_created', table_name='activity_logs')
    op.create_index('ix_activity_logs_task_occurrence_created', 'activity_logs', ['task_occurrence_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_task_occurrence_id'), 'activity_logs', ['task_occurrence_id'], unique=False)
    op.create_foreign_key(None, 'activity_logs', 'task_occurrences', ['task_occurrence_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ai_analyses', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('ai_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('habit_profiles_user_id_key', 'habit_profiles', type_='unique')
    op.drop_index('ix_habit_profiles_user_id', table_name='habit_profiles')
    op.create_index(op.f('ix_habit_profiles_user_id'), 'habit_profiles', ['user_id'], unique=True)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('notifications', 'notification_type',
               existing_type=postgresql.ENUM('schedule_generated', 'task_reminder', 'task_completed', 'task_missed', 'system', name='notificationtype'),
               nullable=False,
               existing_server_default=sa.text("'system'::notificationtype"))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_reminder_history_reminder_id'), 'reminder_history', ['reminder_id'], unique=False)
    op.add_column('reminders', sa.Column('task_occurrence_id', sa.UUID(), nullable=True))
    op.alter_column('reminders', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('reminders', 'reminder_type',
               existing_type=postgresql.ENUM('task', 'meal', 'water', 'sleep', 'medication', 'custom', name='remindertype'),
               nullable=False,
               existing_server_default=sa.text("'custom'::remindertype"))
    op.alter_column('reminders', 'is_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('reminders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_reminders_task_occurrence_id'), 'reminders', ['task_occurrence_id'], unique=False)
    op.drop_constraint('reminders_task_id_fkey', 'reminders', type_='foreignkey')
    op.create_foreign_key(None, 'reminders', 'task_occurrences', ['task_occurrence_id'], ['id'], ondelete='CASCADE')
    op.drop_column('reminders', 'task_id')
    op.alter_column('routines', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('routines', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('routines', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('routines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('routines', 'routine_text')
    op.alter_column('schedules', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('schedules', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'urgent', name='taskpriority'),
               nullable=False,
               existing_server_default=sa.text("'medium'::taskpriority"))
    op.alter_column('schedules', 'status',
               existing_type=postgresql.ENUM('draft', 'active', 'completed', 'cancelled', name='schedulestatus'),
               nullable=False,
               existing_server_default=sa.text("'active'::schedulestatus"))
    op.alter_column('schedules', 'category',
               existing_type=postgresql.ENUM('work', 'study', 'health', 'personal', 'meal', 'sleep', 'other', name='taskcategory'),
               nullable=False,
               existing_server_default=sa.text("'other'::taskcategory"))
    op.alter_column('schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('tasks', sa.Column('travel_time_minutes', sa.Integer(), nullable=False))
    op.alter_column('tasks', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'urgent', name='taskpriority'),
               nullable=False,
               existing_server_default=sa.text("'medium'::taskpriority"))
    op.alter_column('tasks', 'category',
               existing_type=postgresql.ENUM('work', 'study', 'health', 'personal', 'meal', 'sleep', 'other', name='taskcategory'),
               nullable=False,
               existing_server_default=sa.text("'other'::taskcategory"))
    op.alter_column('tasks', 'is_fixed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tasks', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tasks', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('60'))
    op.alter_column('tasks', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('pending', 'in_progress', 'completed', 'skipped', 'cancelled', name='taskstatus'),
               nullable=False,
               existing_server_default=sa.text("'pending'::taskstatus"))
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_tasks_user_status', table_name='tasks')
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.create_index('ix_tasks_user_status', 'tasks', ['user_id', 'status'], unique=False)
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('pending', 'in_progress', 'completed', 'skipped', 'cancelled', name='taskstatus'),
               nullable=True,
               existing_server_default=sa.text("'pending'::taskstatus"))
    op.alter_column('tasks', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('tasks', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('60'))
    op.alter_column('tasks', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('tasks', 'is_fixed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('tasks', 'category',
               existing_type=postgresql.ENUM('work', 'study', 'health', 'personal', 'meal', 'sleep', 'other', name='taskcategory'),
               nullable=True,
               existing_server_default=sa.text("'other'::taskcategory"))
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'urgent', name='taskpriority'),
               nullable=True,
               existing_server_default=sa.text("'medium'::taskpriority"))
    op.alter_column('tasks', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('tasks', 'travel_time_minutes')
    op.alter_column('schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('schedules', 'category',
               existing_type=postgresql.ENUM('work', 'study', 'health', 'personal', 'meal', 'sleep', 'other', name='taskcategory'),
               nullable=True,
               existing_server_default=sa.text("'other'::taskcategory"))
    op.alter_column('schedules', 'status',
               existing_type=postgresql.ENUM('draft', 'active', 'completed', 'cancelled', name='schedulestatus'),
               nullable=True,
               existing_server_default=sa.text("'active'::schedulestatus"))
    op.alter_column('schedules', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'urgent', name='taskpriority'),
               nullable=True,
               existing_server_default=sa.text("'medium'::taskpriority"))
    op.alter_column('schedules', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('routines', sa.Column('routine_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('routines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('routines', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('routines', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('routines', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('reminders', sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reminders', type_='foreignkey')
    op.create_foreign_key('reminders_task_id_fkey', 'reminders', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_reminders_task_occurrence_id'), table_name='reminders')
    op.alter_column('reminders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reminders', 'is_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('reminders', 'reminder_type',
               existing_type=postgresql.ENUM('task', 'meal', 'water', 'sleep', 'medication', 'custom', name='remindertype'),
               nullable=True,
               existing_server_default=sa.text("'custom'::remindertype"))
    op.alter_column('reminders', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('reminders', 'task_occurrence_id')
    op.drop_index(op.f('ix_reminder_history_reminder_id'), table_name='reminder_history')
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'notification_type',
               existing_type=postgresql.ENUM('schedule_generated', 'task_reminder', 'task_completed', 'task_missed', 'system', name='notificationtype'),
               nullable=True,
               existing_server_default=sa.text("'system'::notificationtype"))
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_habit_profiles_user_id'), table_name='habit_profiles')
    op.create_index('ix_habit_profiles_user_id', 'habit_profiles', ['user_id'], unique=False)
    op.create_unique_constraint('habit_profiles_user_id_key', 'habit_profiles', ['user_id'])
    op.alter_column('ai_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_analyses', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.drop_index(op.f('ix_activity_logs_task_occurrence_id'), table_name='activity_logs')
    op.drop_index('ix_activity_logs_task_occurrence_created', table_name='activity_logs')
    op.create_index('ix_activity_logs_task_created', 'activity_logs', ['task_id', 'created_at'], unique=False)
    op.alter_column('activity_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('activity_logs', 'status',
               existing_type=postgresql.ENUM('started', 'completed', 'skipped', name='activitystatus'),
               nullable=True,
               existing_server_default=sa.text("'started'::activitystatus"))
    op.alter_column('activity_logs', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('activity_logs', 'task_occurrence_id')
    op.drop_index('ix_task_occurrences_user_status', table_name='task_occurrences')
    op.drop_index(op.f('ix_task_occurrences_user_id'), table_name='task_occurrences')
    op.drop_index('ix_task_occurrences_user_date', table_name='task_occurrences')
    op.drop_index(op.f('ix_task_occurrences_task_id'), table_name='task_occurrences')
    op.drop_index(op.f('ix_task_occurrences_date'), table_name='task_occurrences')
    op.drop_table('task_occurrences')
    op.drop_index(op.f('ix_user_stats_user_id'), table_name='user_stats')
    op.drop_table('user_stats')
    # ### end Alembic commands ###
