"""add sprint 2 user preferences fields

Revision ID: fa375917bc0f
Revises: 72e74e4a8add
Create Date: 2026-08-09 01:05:13.818952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa375917bc0f'
down_revision: Union[str, None] = '72e74e4a8add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create ENUMs for postgres
    sa.Enum('work', 'study', 'health', 'personal', 'social', 'other', name='routinecategory').create(op.get_bind(), checkfirst=True)
    sa.Enum('low', 'medium', 'high', 'urgent', name='taskpriority').create(op.get_bind(), checkfirst=True)
    sa.Enum('daily', 'weekly', 'monthly', 'custom', name='recurrencetype').create(op.get_bind(), checkfirst=True)
    
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('wake_time', sa.Time(), nullable=True),
    sa.Column('sleep_time', sa.Time(), nullable=True),
    sa.Column('work_start', sa.Time(), nullable=True),
    sa.Column('work_end', sa.Time(), nullable=True),
    sa.Column('college_start', sa.Time(), nullable=True),
    sa.Column('college_end', sa.Time(), nullable=True),
    sa.Column('break_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('preferred_study_time', sa.String(length=32), nullable=True),
    sa.Column('preferred_workout_time', sa.String(length=32), nullable=True),
    sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('working_days', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheduling_style', sa.Enum('strict', 'flexible', name='schedulingstyle'), nullable=True),
    sa.Column('default_buffer_time_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.add_column('notifications', sa.Column('is_delivered', sa.Boolean(), nullable=False))
    op.add_column('reminders', sa.Column('is_snoozed', sa.Boolean(), nullable=False))
    op.add_column('reminders', sa.Column('snooze_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reminders', sa.Column('is_completed', sa.Boolean(), nullable=False))
    op.add_column('routines', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('routines', sa.Column('category', sa.Enum('work', 'study', 'health', 'personal', 'social', 'other', name='routinecategory'), nullable=False))
    op.add_column('routines', sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='taskpriority'), nullable=False))
    op.add_column('routines', sa.Column('frequency', sa.Enum('daily', 'weekly', 'monthly', 'custom', name='recurrencetype'), nullable=True))
    op.add_column('routines', sa.Column('estimated_duration', sa.Integer(), nullable=False))
    op.add_column('routines', sa.Column('preferred_time', sa.Time(), nullable=True))
    op.add_column('routines', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tasks', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'labels')
    op.drop_column('tasks', 'notes')
    op.drop_column('routines', 'tags')
    op.drop_column('routines', 'preferred_time')
    op.drop_column('routines', 'estimated_duration')
    op.drop_column('routines', 'frequency')
    op.drop_column('routines', 'priority')
    op.drop_column('routines', 'category')
    op.drop_column('routines', 'description')
    op.drop_column('reminders', 'is_completed')
    op.drop_column('reminders', 'snooze_until')
    op.drop_column('reminders', 'is_snoozed')
    op.drop_column('notifications', 'is_delivered')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
