"""add longest_streak to user_stats

Revision ID: fc2c2f33da3a
Revises: 02d100681e1c
Create Date: 2026-08-22 11:10:07.572480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc2c2f33da3a'
down_revision: Union[str, None] = '02d100681e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stats', sa.Column('longest_streak', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stats', 'longest_streak')
    # ### end Alembic commands ###
